services:
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup --label-enable
        restart: always
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        environment:
            - WATCHTOWER_NOTIFICATIONS=shoutrrr
            - WATCHTOWER_NOTIFICATIONS_HOSTNAME=$UPDATE_NOTIFICATION_HOST
            - WATCHTOWER_NOTIFICATION_URL=$UPDATE_NOTIFICATION_URL
    backend:
        ports:
            - "127.0.0.1:8000:8000"
        labels:
          com.centurylinklabs.watchtower.enable: "true"
        volumes: !override
            - tmvis_data:/data

volumes:
    tmvis_data:
      driver_opts:
        type: "nfs"
        o: "addr=$NAS_ADDR,nolock,soft,rw,acl,nfsvers=3"
        device: "$NAS_PATH"
