services:
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup --label-enable
        restart: always
        networks:
            - caddy
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
    caddy:
        volumes:
            - caddy-log:/var/log
    backend:
        labels:
          com.centurylinklabs.watchtower.enable: "true"
          caddy_0.log: "{}"
          caddy_0.log.level: error
          caddy_0.log.output: file /var/log/caddy.log
          caddy_0.log.output.roll_size: 10MiB
          caddy_0.log.output.roll_keep: 10
          caddy_0.log.output.roll_keep_for: 720h
        volumes: !override
            - tmvis_data:/app/data

volumes:
    tmvis_data:
      driver_opts:
        type: "nfs"
        o: "addr=$NAS_ADDR,nolock,soft,rw,acl,nfsvers=3"
        device: "$NAS_PATH"
    caddy-log:
