services:
    backend:
        image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
        restart: always
        command: ["fastapi", "run", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "app/main.py"]
        env_file:
            - .env
        environment:
            - DOMAIN=${API_DOMAIN}
            - ENVIRONMENT=${NODE_ENV}
            - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
            - SENTRY_DSN_BACKEND=${SENTRY_DSN_BACKEND}
            - SQLITE_DATABASE_PATH=${SQLITE_DATABASE_PATH}
        volumes:
            - ./backend/data/tmvis.db:/app/data/tmvis.db:ro
        build:
            context: .
            dockerfile: backend.Dockerfile
            args:
                INSTALL_DEV: false
        platform: linux/amd64
