services:
  backend:
    restart: "no"
    volumes:
      - ./backend/app:/app/app
    build:
      args:
        INSTALL_DEV: true
    develop:
      watch:
        - action: sync
          path: backend/app/
          target: /app/app/
        - action: rebuild
          path: backend/pyproject.toml
    command: "fastapi DEV --host 0.0.0.0 --port 8000 app/main.py"
    labels:
      caddy_0: http://localhost
      caddy_0.@match.path: /api /api/* /docs /docs/* /redoc /redoc/*
      caddy_0.reverse_proxy_0: "@match backend:8000"


  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    restart: "always"
    networks:
      - caddy
    develop:
      watch:
        - action: sync
          path: frontend/src/
          target: /app/src/
        - action: rebuild
          path: frontend/package.json
        - action: rebuild
          path: frontend/pnpm-lock.yaml
    command: ["pnpm", "dev", "--port", "5173", "--host", "0.0.0.0"]
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - ./shared:/app/src/lib/assets/shared
      - notused:/app/node_modules
    build:
      context: .
      dockerfile: frontend.Dockerfile
      target: dev
    platform: linux/amd64
    labels:
      caddy_0: http://localhost
      caddy_0.reverse_proxy_1: "frontend:5173"

volumes:
  notused:
