/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */

export type Topology = typeof Topology[keyof typeof Topology];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Topology = {
  All: 'All',
  Both: 'Both',
  'Alpha-helix': 'Alpha-helix',
  'Beta-strand': 'Beta-strand',
} as const;
