/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */
import type { LabelInfo } from './labelInfo';

export interface AnnotationLegend {
  description: string;
  labels: LabelInfo[];
  name: string;
}
