/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */

export type Clade = typeof Clade[keyof typeof Clade];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Clade = {
  Asgard_group: 'Asgard group',
  Candidatus_Hydrothermarchaeota: 'Candidatus Hydrothermarchaeota',
  Candidatus_Thermoplasmatota: 'Candidatus Thermoplasmatota',
  DPANN_group: 'DPANN group',
  Euryarchaeota: 'Euryarchaeota',
  TACK_group: 'TACK group',
  Archaea_incertae_sedis: 'Archaea incertae sedis',
  unclassified_Archaea: 'unclassified Archaea',
  environmental_samples: 'environmental samples',
  Amoebozoa: 'Amoebozoa',
  Ancyromonadida: 'Ancyromonadida',
  Apusozoa: 'Apusozoa',
  Breviatea: 'Breviatea',
  CRuMs: 'CRuMs',
  'Cryptophyceae_(cryptomonads)': 'Cryptophyceae (cryptomonads)',
  Discoba: 'Discoba',
  Glaucocystophyceae: 'Glaucocystophyceae',
  Haptista: 'Haptista',
  Hemimastigophora: 'Hemimastigophora',
  Malawimonadida: 'Malawimonadida',
  Metamonada: 'Metamonada',
  Opisthokonta: 'Opisthokonta',
  Rhodelphea: 'Rhodelphea',
  'Rhodophyta_(red_algae)': 'Rhodophyta (red algae)',
  Sar: 'Sar',
  Viridiplantae: 'Viridiplantae',
  Eukaryota_incertae_sedis: 'Eukaryota incertae sedis',
  unclassified_eukaryotes: 'unclassified eukaryotes',
  Acidobacteria: 'Acidobacteria',
  Aquificae: 'Aquificae',
  Atribacterota: 'Atribacterota',
  'Caldiserica/Cryosericota_group': 'Caldiserica/Cryosericota group',
  Calditrichaeota: 'Calditrichaeota',
  Candidatus_Krumholzibacteriota: 'Candidatus Krumholzibacteriota',
  Candidatus_Tharpellota: 'Candidatus Tharpellota',
  Chrysiogenetes: 'Chrysiogenetes',
  Coleospermum: 'Coleospermum',
  Coprothermobacterota: 'Coprothermobacterota',
  Deferribacteres: 'Deferribacteres',
  Desulfobacterota: 'Desulfobacterota',
  Dictyoglomi: 'Dictyoglomi',
  Elusimicrobia: 'Elusimicrobia',
  FCB_group: 'FCB group',
  Fusobacteria: 'Fusobacteria',
  Myxococcota: 'Myxococcota',
  'Nitrospinae/Tectomicrobia_group': 'Nitrospinae/Tectomicrobia group',
  Nitrospirae: 'Nitrospirae',
  Proteobacteria: 'Proteobacteria',
  PVC_group: 'PVC group',
  Spirochaetes: 'Spirochaetes',
  Synergistetes: 'Synergistetes',
  Terrabacteria_group: 'Terrabacteria group',
  Thermodesulfobacteria: 'Thermodesulfobacteria',
  Thermotogae: 'Thermotogae',
  Bacteria_incertae_sedis: 'Bacteria incertae sedis',
  unclassified_Bacteria: 'unclassified Bacteria',
} as const;
