/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */

export type DatabaseType = typeof DatabaseType[keyof typeof DatabaseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseType = {
  tmbed: 'tmbed',
  topdb: 'topdb',
  membranome: 'membranome',
  uniprot: 'uniprot',
  tmalphafold: 'tmalphafold',
} as const;
