/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */
import type { AnnotationLegend } from './annotationLegend';

export type GetDbAnnotationsLegends200 = {[key: string]: AnnotationLegend};
