/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */
import type { PageInfoNextCursor } from './pageInfoNextCursor';

export interface PageInfo {
  has_next_page: boolean;
  next_cursor?: PageInfoNextCursor;
}
