/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinInfo } from './proteinInfo';

export interface ProteinResponse {
  items: ProteinInfo[];
  total_count: number;
}
