/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */
import type { PageInfo } from './pageInfo';

export type ProteinResponsePageInfo = PageInfo | null;
