/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * TMVis
 * OpenAPI spec version: 0.1.0
 */

export type SuperKingdom = typeof SuperKingdom[keyof typeof SuperKingdom];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuperKingdom = {
  Archaea: 'Archaea',
  Eukaryota: 'Eukaryota',
  Bacteria: 'Bacteria',
  unclassified_sequences: 'unclassified sequences',
} as const;
