"""Include all models

Revision ID: 5e0282159f91
Revises:
Create Date: 2024-10-21 12:04:37.935839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5e0282159f91"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence",
        "sequence",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_alpha_helix",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_beta_strand",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_signal",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "tm_helix_percent",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "tm_strand_percent",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "signal_percent",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_index(
        "ix_tm_info_has_alpha_helix_has_beta_strand_has_signal", table_name="tminfo"
    )
    op.create_index(
        "ix_tminfo_has_alpha_helix_has_beta_strand_has_signal",
        "tminfo",
        ["has_alpha_helix", "has_beta_strand", "has_signal"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tminfo_has_alpha_helix_has_beta_strand_has_signal", table_name="tminfo"
    )
    op.create_index(
        "ix_tm_info_has_alpha_helix_has_beta_strand_has_signal",
        "tminfo",
        ["has_alpha_helix", "has_beta_strand", "has_signal"],
        unique=False,
    )
    op.alter_column(
        "tminfo",
        "signal_percent",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "tm_strand_percent",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "tm_helix_percent",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_signal",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_beta_strand",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "tminfo",
        "has_alpha_helix",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "sequence",
        "sequence",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
