# This file is autogenerated by scripts/generate-enums.sh
# cspell:disable

from enum import Enum


class SuperKingdom(str, Enum):
    Archaea = "Archaea"
    Eukaryota = "Eukaryota"
    Bacteria = "Bacteria"
    unclassified_sequences = "unclassified sequences"


class Clade(str, Enum):
    Asgard_group = "Asgard group"
    Candidatus_Hydrothermarchaeota = "Candidatus Hydrothermarchaeota"
    Candidatus_Thermoplasmatota = "Candidatus Thermoplasmatota"
    DPANN_group = "DPANN group"
    Euryarchaeota = "Euryarchaeota"
    TACK_group = "TACK group"
    Archaea_incertae_sedis = "Archaea incertae sedis"
    unclassified_Archaea = "unclassified Archaea"
    environmental_samples = "environmental samples"
    Amoebozoa = "Amoebozoa"
    Ancyromonadida = "Ancyromonadida"
    Apusozoa = "Apusozoa"
    Breviatea = "Breviatea"
    CRuMs = "CRuMs"
    Cryptophyceae_cryptomonads = "Cryptophyceae (cryptomonads)"
    Discoba = "Discoba"
    Glaucocystophyceae = "Glaucocystophyceae"
    Haptista = "Haptista"
    Hemimastigophora = "Hemimastigophora"
    Malawimonadida = "Malawimonadida"
    Metamonada = "Metamonada"
    Opisthokonta = "Opisthokonta"
    Rhodelphea = "Rhodelphea"
    Rhodophyta_red_algae = "Rhodophyta (red algae)"
    Sar = "Sar"
    Viridiplantae = "Viridiplantae"
    Eukaryota_incertae_sedis = "Eukaryota incertae sedis"
    unclassified_eukaryotes = "unclassified eukaryotes"
    Acidobacteria = "Acidobacteria"
    Aquificae = "Aquificae"
    Atribacterota = "Atribacterota"
    Caldiserica_Cryosericota_group = "Caldiserica/Cryosericota group"
    Calditrichaeota = "Calditrichaeota"
    Candidatus_Krumholzibacteriota = "Candidatus Krumholzibacteriota"
    Candidatus_Tharpellota = "Candidatus Tharpellota"
    Chrysiogenetes = "Chrysiogenetes"
    Coleospermum = "Coleospermum"
    Coprothermobacterota = "Coprothermobacterota"
    Deferribacteres = "Deferribacteres"
    Desulfobacterota = "Desulfobacterota"
    Dictyoglomi = "Dictyoglomi"
    Elusimicrobia = "Elusimicrobia"
    FCB_group = "FCB group"
    Fusobacteria = "Fusobacteria"
    Myxococcota = "Myxococcota"
    Nitrospinae_Tectomicrobia_group = "Nitrospinae/Tectomicrobia group"
    Nitrospirae = "Nitrospirae"
    Proteobacteria = "Proteobacteria"
    PVC_group = "PVC group"
    Spirochaetes = "Spirochaetes"
    Synergistetes = "Synergistetes"
    Terrabacteria_group = "Terrabacteria group"
    Thermodesulfobacteria = "Thermodesulfobacteria"
    Thermotogae = "Thermotogae"
    Bacteria_incertae_sedis = "Bacteria incertae sedis"
    unclassified_Bacteria = "unclassified Bacteria"


SK_CLADE_MAPPING: dict[SuperKingdom, list[Clade]] = {
    SuperKingdom.Archaea: [
        Clade.Asgard_group,
        Clade.Candidatus_Hydrothermarchaeota,
        Clade.Candidatus_Thermoplasmatota,
        Clade.DPANN_group,
        Clade.Euryarchaeota,
        Clade.TACK_group,
        Clade.Archaea_incertae_sedis,
        Clade.unclassified_Archaea,
        Clade.environmental_samples,
    ],
    SuperKingdom.Eukaryota: [
        Clade.Amoebozoa,
        Clade.Ancyromonadida,
        Clade.Apusozoa,
        Clade.Breviatea,
        Clade.CRuMs,
        Clade.Cryptophyceae_cryptomonads,
        Clade.Discoba,
        Clade.Glaucocystophyceae,
        Clade.Haptista,
        Clade.Hemimastigophora,
        Clade.Malawimonadida,
        Clade.Metamonada,
        Clade.Opisthokonta,
        Clade.Rhodelphea,
        Clade.Rhodophyta_red_algae,
        Clade.Sar,
        Clade.Viridiplantae,
        Clade.Eukaryota_incertae_sedis,
        Clade.unclassified_eukaryotes,
        Clade.environmental_samples,
    ],
    SuperKingdom.Bacteria: [
        Clade.Acidobacteria,
        Clade.Aquificae,
        Clade.Atribacterota,
        Clade.Caldiserica_Cryosericota_group,
        Clade.Calditrichaeota,
        Clade.Candidatus_Krumholzibacteriota,
        Clade.Candidatus_Tharpellota,
        Clade.Chrysiogenetes,
        Clade.Coleospermum,
        Clade.Coprothermobacterota,
        Clade.Deferribacteres,
        Clade.Desulfobacterota,
        Clade.Dictyoglomi,
        Clade.Elusimicrobia,
        Clade.FCB_group,
        Clade.Fusobacteria,
        Clade.Myxococcota,
        Clade.Nitrospinae_Tectomicrobia_group,
        Clade.Nitrospirae,
        Clade.Proteobacteria,
        Clade.PVC_group,
        Clade.Spirochaetes,
        Clade.Synergistetes,
        Clade.Terrabacteria_group,
        Clade.Thermodesulfobacteria,
        Clade.Thermotogae,
        Clade.Bacteria_incertae_sedis,
        Clade.unclassified_Bacteria,
        Clade.environmental_samples,
    ],
    SuperKingdom.unclassified_sequences: [],
}
