# This file is autogenerated by scripts/generate-enums.sh
from enum import Enum


class SuperKingdomEnum(str, Enum):
    Archaea = "Archaea"
    Eukaryota = "Eukaryota"
    Bacteria = "Bacteria"
    unclassified_sequences = "unclassified sequences"


class CladeEnum(str, Enum):
    Asgard_group = "Asgard group"
    Candidatus_Hydrothermarchaeota = "Candidatus Hydrothermarchaeota"
    Candidatus_Thermoplasmatota = "Candidatus Thermoplasmatota"
    DPANN_group = "DPANN group"
    Euryarchaeota = "Euryarchaeota"
    TACK_group = "TACK group"
    Archaea_incertae_sedis = "Archaea incertae sedis"
    unclassified_Archaea = "unclassified Archaea"
    environmental_samples = "environmental samples"
    Amoebozoa = "Amoebozoa"
    Ancyromonadida = "Ancyromonadida"
    Apusozoa = "Apusozoa"
    Breviatea = "Breviatea"
    CRuMs = "CRuMs"
    Cryptophyceae_cryptomonads = "Cryptophyceae (cryptomonads)"
    Discoba = "Discoba"
    Glaucocystophyceae = "Glaucocystophyceae"
    Haptista = "Haptista"
    Hemimastigophora = "Hemimastigophora"
    Malawimonadida = "Malawimonadida"
    Metamonada = "Metamonada"
    Opisthokonta = "Opisthokonta"
    Rhodelphea = "Rhodelphea"
    Rhodophyta_red_algae = "Rhodophyta (red algae)"
    Sar = "Sar"
    Viridiplantae = "Viridiplantae"
    Eukaryota_incertae_sedis = "Eukaryota incertae sedis"
    unclassified_eukaryotes = "unclassified eukaryotes"
    Acidobacteria = "Acidobacteria"
    Aquificae = "Aquificae"
    Atribacterota = "Atribacterota"
    Caldiserica_Cryosericota_group = "Caldiserica/Cryosericota group"
    Calditrichaeota = "Calditrichaeota"
    Candidatus_Krumholzibacteriota = "Candidatus Krumholzibacteriota"
    Candidatus_Tharpellota = "Candidatus Tharpellota"
    Chrysiogenetes = "Chrysiogenetes"
    Coleospermum = "Coleospermum"
    Coprothermobacterota = "Coprothermobacterota"
    Deferribacteres = "Deferribacteres"
    Desulfobacterota = "Desulfobacterota"
    Dictyoglomi = "Dictyoglomi"
    Elusimicrobia = "Elusimicrobia"
    FCB_group = "FCB group"
    Fusobacteria = "Fusobacteria"
    Myxococcota = "Myxococcota"
    Nitrospinae_Tectomicrobia_group = "Nitrospinae/Tectomicrobia group"
    Nitrospirae = "Nitrospirae"
    Proteobacteria = "Proteobacteria"
    PVC_group = "PVC group"
    Spirochaetes = "Spirochaetes"
    Synergistetes = "Synergistetes"
    Terrabacteria_group = "Terrabacteria group"
    Thermodesulfobacteria = "Thermodesulfobacteria"
    Thermotogae = "Thermotogae"
    Bacteria_incertae_sedis = "Bacteria incertae sedis"
    unclassified_Bacteria = "unclassified Bacteria"


SK_CLADE_MAPPING = {
    SuperKingdomEnum.Archaea: [
        CladeEnum.Asgard_group,
        CladeEnum.Candidatus_Hydrothermarchaeota,
        CladeEnum.Candidatus_Thermoplasmatota,
        CladeEnum.DPANN_group,
        CladeEnum.Euryarchaeota,
        CladeEnum.TACK_group,
        CladeEnum.Archaea_incertae_sedis,
        CladeEnum.unclassified_Archaea,
        CladeEnum.environmental_samples,
    ],
    SuperKingdomEnum.Eukaryota: [
        CladeEnum.Amoebozoa,
        CladeEnum.Ancyromonadida,
        CladeEnum.Apusozoa,
        CladeEnum.Breviatea,
        CladeEnum.CRuMs,
        CladeEnum.Cryptophyceae_cryptomonads,
        CladeEnum.Discoba,
        CladeEnum.Glaucocystophyceae,
        CladeEnum.Haptista,
        CladeEnum.Hemimastigophora,
        CladeEnum.Malawimonadida,
        CladeEnum.Metamonada,
        CladeEnum.Opisthokonta,
        CladeEnum.Rhodelphea,
        CladeEnum.Rhodophyta_red_algae,
        CladeEnum.Sar,
        CladeEnum.Viridiplantae,
        CladeEnum.Eukaryota_incertae_sedis,
        CladeEnum.unclassified_eukaryotes,
        CladeEnum.environmental_samples,
    ],
    SuperKingdomEnum.Bacteria: [
        CladeEnum.Acidobacteria,
        CladeEnum.Aquificae,
        CladeEnum.Atribacterota,
        CladeEnum.Caldiserica_Cryosericota_group,
        CladeEnum.Calditrichaeota,
        CladeEnum.Candidatus_Krumholzibacteriota,
        CladeEnum.Candidatus_Tharpellota,
        CladeEnum.Chrysiogenetes,
        CladeEnum.Coleospermum,
        CladeEnum.Coprothermobacterota,
        CladeEnum.Deferribacteres,
        CladeEnum.Desulfobacterota,
        CladeEnum.Dictyoglomi,
        CladeEnum.Elusimicrobia,
        CladeEnum.FCB_group,
        CladeEnum.Fusobacteria,
        CladeEnum.Myxococcota,
        CladeEnum.Nitrospinae_Tectomicrobia_group,
        CladeEnum.Nitrospirae,
        CladeEnum.Proteobacteria,
        CladeEnum.PVC_group,
        CladeEnum.Spirochaetes,
        CladeEnum.Synergistetes,
        CladeEnum.Terrabacteria_group,
        CladeEnum.Thermodesulfobacteria,
        CladeEnum.Thermotogae,
        CladeEnum.Bacteria_incertae_sedis,
        CladeEnum.unclassified_Bacteria,
        CladeEnum.environmental_samples,
    ],
    SuperKingdomEnum.unclassified_sequences: [],
}
