name: "Docker Release Tagger"
description: "Creates and pushes multiple Docker tags for semantic versioning"

inputs:
  release_tag:
    description: "The new release tag (e.g. 1.2.3)"
    required: true
  registry:
    description: "The Docker registry to push the tags to"
    required: true
  image_name:
    description: "The Docker image name to tag"
    required: true
  old_tag:
    description: "The existing tag to base the new tags on"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate and apply tags
      shell: bash
      env:
        IMAGE: ${{ inputs.registry }}/${{ inputs.image_name }}
      run: |
        # Parse version components
        version="${{ inputs.release_tag }}"
        major=$(echo $version | cut -d. -f1)
        minor=$(echo $version | cut -d. -f2)

        # Pull the source image
        docker pull $IMAGE:${{ inputs.old_tag }}

        # Create and push each tag
        for new_tag in "$version" "$major.$minor" "$major" "latest"; do
          echo "Creating tag: $new_tag"
          docker tag $IMAGE:${{ inputs.old_tag }} $IMAGE:$new_tag
          docker push $IMAGE:$new_tag
        done
