name: Create Docker Releases

on:
    workflow_call:
        inputs:
            release_tag:
                required: true
                type: string
            image_name:
                required: true
                type: string
            old_tag:
                required: true
                type: string

jobs:
    tag:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Generate and apply tags
              run: |
                  # Parse version components
                  version="${{ inputs.release_tag }}"
                  major=$(echo $version | cut -d. -f1)
                  minor=$(echo $version | cut -d. -f2)

                  # Pull the source image
                  docker pull ${{ inputs.image_name }}:${{ inputs.old_tag }}

                  # Create and push each tag
                  for new_tag in "$version" "$major.$minor" "$major" "latest"; do
                    echo "Creating tag: $new_tag"
                    docker tag ${{ inputs.image_name }}:${{ inputs.old_tag }} ${{ inputs.image_name }}:$new_tag
                    docker push ${{ inputs.image_name }}:$new_tag
                  done
