name: Create Docker Releases

on:
    workflow_call:
        inputs:
            release_tag:
                required: true
                type: string
            image_name:
                required: true
                type: string
            old_tag:
                required: true
                type: string

jobs:
    tag:
        runs-on: ubuntu-latest
        environment: production
        outputs:
            tags: ${{ steps.meta-frontend.outputs.tags }}
        steps:
            - name: Extract Frontend metadata
              id: meta-frontend
              uses: docker/metadata-action@v5
              with:
                  images: ${{ inputs.image_name }}
                  tags: |
                      type=semver,pattern={{version}},value=${{ inputs.release_tag }}
                      type=semver,pattern={{major}}.{{minor}},value=${{ inputs.release_tag }}
                      type=semver,pattern={{major}},value=${{ inputs.release_tag }}
                      type=raw,value=latest
    retag:
        runs-on: ubuntu-latest
        needs: tag
        strategy:
            matrix:
                tags: ${{ needs.tag.outputs.tags }}
        steps:
            - name: Pull Image
              run: docker pull ${{ inputs.image_name }}:${{ inputs.old_tag }}
            - name: Retag Image
              run: docker tag ${{ inputs.image_name }}:${{ inputs.old_tag }} ${{ matrix.tags }}
            - name: Push Image
              run: docker push ${{ matrix.tags }}
