name: Build Frontend

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string

jobs:
    build:
        outputs:
            build_artifact: ${{ steps.build-artifact.outputs.build_artifact }}
        runs-on: ubuntu-latest
        environment: production
        permissions:
            contents: read
            packages: read
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ inputs.tag }}

            - name: Build in Docker
              uses: addnab/docker-run-action@v3
              with:
                  registry: ${{ vars.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  image: ${{vars.REGISTRY}}/${{ vars.FRONTEND_IMAGE_NAME }}:main-dev
                  options: |
                      -v ${{ github.workspace }}/frontend:/app
                      -v ${{ github.workspace }}/shared:/app/src/lib/assets/shared
                      -e NODE_ENV=production
                      -e PUBLIC_API_URL=${{ vars.PUBLIC_API_URL }}
                      -e PUBLIC_GITHUB_REPO=${{ github.repository }}
                      -e PUBLIC_MIN_PROTEIN_LENGTH=${{ vars.PUBLIC_MIN_PROTEIN_LENGTH }}
                      -e PUBLIC_MAX_PROTEIN_LENGTH=${{ vars.PUBLIC_MAX_PROTEIN_LENGTH }}
                      -e PUBLIC_MAINTENANCE_MODE=${{ vars.PUBLIC_MAINTENANCE_MODE }}
                      -e PUBLIC_PROJECT_NAME=${{ vars.PUBLIC_PROJECT_NAME }}
                  run: pnpm exec svelte-kit sync  && pnpm run build

            - name: Upload build artifact
              id: build-artifact
              uses: actions/upload-artifact@v4
              with:
                  include-hidden-files: true
                  name: frontend-build
                  path: .svelte-kit/cloudflare/
                  retention-days: 1
