name: Generate Client

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    # Setup Python
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "0.4.9"
        enable-cache: true
        cache-suffix: "uv-cache"
        cache-dependency-glob: "backend/uv.lock"

    - name: Install Python 3.12
      run: uv python install 3.12

    # Setup PNPM
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    # Install Frontend/ Backend dependencies
    - name: Install Frontend dependencies
      run: pnpm install --frozen-lockfile
      working-directory: frontend

    - name: Install Python dependencies
      run: uv install --frozen
      working-directory: backend

    - name: Generate client
      run: bash scripts/generate-client.sh

    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add frontend/src/client
        git diff --staged --quiet || git commit -m "✨ Autogenerate frontend client"
        git push

  # https://github.com/marketplace/actions/alls-green#why
  generate-client-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - generate-client
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
